### ISSUE TITLE
Issue with figures that are connected to each other

### ISSUE THREAD

**Issue by chrise96** [karlobermeyer/VisiLibity1#2]
The visibility polygon is improperly generated when sides of multiple figures are connected to each other (same coordinates).

I used the VisiLibity1 Python example to recreate this issue. See the image below. The blue line is the visibility polygon.

<img width="400" alt="Schermafbeelding 2020-04-01 om 16 42 10" src="https://user-images.githubusercontent.com/22835281/78152795-9a11bb80-743a-11ea-8da0-41bfb5a63c5a.png">

**Comment by karlobermeyer** [comment]
Environments must have non-intersecting polygons with an epsilon of clearance between them. See https://karlobermeyer.github.io/VisiLibity1/use_notes/VisiLibity_FAQ.html

I recommend you either separate or merge the problem polygons.
