### ISSUE TITLE
Redundant Q insertion in shortest_path calculation?

### ISSUE THREAD

**Issue by hawkinsw** [karlobermeyer/VisiLibity1#3]
Dr. Obermeyer,

First, thank you for the great work on this library! I know that you are incredibly busy and it's great that you take the time to publish and maintain this for the community.

I am looking through the library and trying to dissect it. I came across something interesting in visilibity.cpp at line 2371 (https://github.com/karlobermeyer/VisiLibity1/blob/master/src/visilibity.cpp#L2371). 

It seems to me that this insertion into Q of a node that is not already in the search tree is duplicative of the insertion on line 2348 (https://github.com/karlobermeyer/VisiLibity1/blob/master/src/visilibity.cpp#L2348). However, I am sure that *I* am the one missing something and I was hoping that you could help me understand what I am missing. 

Again, thank you for the great work on this library and your commitment to maintaining it for the community. 

Will

**Comment by karlobermeyer** [comment]
As in private correspondence, the insertion seems to be indeed redundant. The algorithm is correct as is, but the redundancy should be eliminated for efficiency and code clarity.
